version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - seguros-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - CLEAR_TMP_FOLDER=0
      - SKIP_INFRA_DOWNLOADS=1
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
    volumes:
      - localstack-data:/tmp/localstack/data
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f http://localhost:4566/ || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    networks:
      - seguros-network

  proposta-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: proposta
    container_name: proposta-service
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      init-localstack:
        condition: service_completed_successfully
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Host=postgres;Port=5432;Database=proposta_db;Username=postgres;Password=postgres
      - LocalStack__UseLocalStack=true
      - LocalStack__LocalStackHost=localstack
      - LocalStack__LocalStackPort=4566
      - AWS__Region=us-east-1
      - AWS__SQS__PropostaStatusQueue=proposta-status-queue
    networks:
      - seguros-network

  contratacao-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: contratacao
    container_name: contratacao-service
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      init-localstack:
        condition: service_completed_successfully
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Host=postgres;Port=5432;Database=contratacao_db;Username=postgres;Password=postgres
      - LocalStack__UseLocalStack=true
      - LocalStack__LocalStackHost=localstack
      - LocalStack__LocalStackPort=4566
      - AWS__Region=us-east-1
      - AWS__SQS__PropostaStatusQueue=proposta-status-queue
    networks:
      - seguros-network

  init-localstack:
    image: amazon/aws-cli:latest
    container_name: init-localstack
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 30 &&
      aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name proposta-status-queue &&
      aws --endpoint-url=http://localstack:4566 sqs get-queue-url --queue-name proposta-status-queue"
    restart: on-failure:3
    networks:
      - seguros-network

  init-postgres:
    image: postgres:latest
    container_name: init-postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGPASSWORD=postgres
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 5 &&
      psql -h postgres -U postgres -c 'CREATE DATABASE proposta_db;' &&
      psql -h postgres -U postgres -c 'CREATE DATABASE contratacao_db;'"
    networks:
      - seguros-network

volumes:
  postgres-data:
  localstack-data:
    driver: local

networks:
  seguros-network:
    driver: bridge